services:
  web:
    image: zoredeaxx/surftg:web
    restart: always
    ports:
      - 8000:8000
    networks:
      - surftg

  cf:
    image: zoredeaxx/surftg:cf
    restart: always
    ports:
      - 8001:8001
    depends_on:
      - web
    networks:
      - surftg

networks:
  surftg:
